# Site settings
title: StarterSquad
email: hello@startersquad.com
description: "Our team of professionals works for startups only. Serious and invested, we will develop your idea and take your project to the next level."
url: "https://www.startersquad.com"
twitter_username: StarterSquad
github_username:  StarterSquad

# Build settings
gems: [jekyll-sass]
markdown: kramdown
permalink: pretty
