# Site settings
title: StarterSquad
email: hello@startersquad.com
description: "Our team of professionals works for startups only. Serious and invested, we will develop your idea and take your project to the next level."
baseurl: ""
url: "https://www.startersquad.com"
facebook_username: startersquad
github_username:  StarterSquad
google_username:  StarterSquad
twitter_username: StarterSquad

# Menu structure
menu:
- title: "Startups"
  url:  "/startups/"
- title: "Services"
  url: "/services/"
- title: "Team"
  url:  "/team/"
- title: "Blog"
  url:  "/blog/"
- title: "Contact"
  url:  "/contact/"

# Build settings
highlighter: pygments
markdown: kramdown
permalink: /blog/:title
assets:
  cache: false
  css_compressor: sass
  gzip: ['text/css', 'application/javascript']
